### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ZobelOmry** [jacekkopecky/node-simple-google-openid#1]
I get authenticated no matter which id token i pass.
Might be because the Client Id configured is not working - but there is no error indicating that.
For me it makes this project obsolete and that's too bad because it's exactly what i need :(

**Comment by jacekkopecky** [comment]
Hi, can you please include code that demonstrates you get authenticated with any tokens? I'd love to help (or even see that my code no longer works and fix it) but I can't with just your issue description.

**Comment by jacekkopecky** [comment]
Closing the issue because there isn't enough information. Feel free to reopen it if you can clarify the situation please – if there indeed is a bug, I'd really like to know and fix it.
