### ISSUE TITLE
error from you code because of missing bracket most likely 

### ISSUE THREAD

**Issue by UP822718** [jacekkopecky/node-simple-google-openid#2]
can you fix your code plz
![image](https://user-images.githubusercontent.com/36608060/52572541-ee5d7480-2e0f-11e9-93ef-f630deb485ba.png)

**Comment by jacekkopecky** [comment]
Hi, can you please report your version of Node.js and simple-google-openid? The first one comes from `node -v` and the second one is in `node_modules/simple-google-openid/package.json`.

**Comment by jacekkopecky** [comment]
closing due to lack of response
